#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------
# Written By George Goldberg (georgeg@il.ibm.com)
---
- name: ensure swift-storage packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    force: yes
    update_cache: yes 
    cache_valid_time: 600
  with_items: debian_packages

- name: ensure services are stopped
  service: 
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes  
  with_items: debian_services


- name: create directories if not already there
  file:
    path: "{{ item }}"
    owner: "swift"
    group: "swift"
    mode: 0750
    state: directory
  with_items:
    - /etc/swift
    - /srv/node
    - /var/lib/swift
    - /var/cache/swift

- name: update configuration files from templates
  template: 
    src: etc/swift/{{ openstack_version }}/{{ item }}
    dest: /etc/swift/{{ item }}
    owner: "swift"
    group: "swift"
    mode: 0600
  with_items: config_files

- name: update rsyncd.conf from template
  template: 
    src: etc/rsyncd.conf 
    dest: /etc/rsyncd.conf 
    owner: root 
    group: root 
    mode: 0644

- name: enable rsync in /etc/default
  command: sed -i '/^RSYNC_ENABLE=/s/false/true/' /etc/default/rsync

- name: ensure rsync service is started
  service: 
    name: rsync
    state: restarted 
    enabled: yes
