#---------------------------------------------------------------------------
# Copyright IBM Corp. 2015, 2015 All Rights Reserved
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# Limitations under the License.
#---------------------------------------------------------------------------
# Written By George Goldberg (georgeg@il.ibm.com)
---
- name: create rings
  hosts: swift-ring-builder
  sudo: True
  gather_facts: True
  vars:
    object_devices: "{{ hostvars|extractfromdict(groups['swift-storage'])|map('propagatevalue','swift_devices.object_devices','device', {'ring':'rings_info','ring.port':'object_server_port'}) | listflatten | addfield('type','object') }}"
    container_devices: "{{ hostvars|extractfromdict(groups['swift-storage'])|map('propagatevalue','swift_devices.container_devices','device', {'ring':'rings_info','ring.port':'container_server_port'}) | listflatten | addfield('type','container') }}"
    all_devices: "{{ hostvars|extractfromdict(groups['swift-storage'])|map('propagatevalue','swift_devices.account_devices','device', {'ring':'rings_info','ring.port':'account_server_port'}) | listflatten | addfield('type','account') + container_devices + object_devices }}"
  tasks:
  roles:
  - role: swift-create-rings 
    devices: "{{ all_devices }}"
   
- name: distribute rings
  hosts: swift-proxy:swift-storage
  sudo: True
  gather_facts: True
  roles:
   - role: swift-distribute-rings
